#!/bin/bash
# set -x
OPTSTRING=":X"

NUKE_LAZYVIM=${NUKE_LAZYVIM:-}

while getopts ${OPTSTRING} opt; do
    case ${opt} in
    X)
        NUKE_LAZYVIM=1
        ;;
    esac
done

if [ ! -z "$NUKE_LAZYVIM" ]; then
    echo "info: nuking old config..."
    if [ -d "$HOME/.local/share/nvim" ]; then
        rm -fr "$HOME/.local/share/nvim"
    fi
    if [ -d "$HOME/.config/nvim" ]; then
        rm -fr "$HOME/.config/nvim"
    fi
fi

if [ ! -d ~/.config/nvim ]; then
    echo "info: cloning LazyVim..."
    git clone https://github.com/LazyVim/starter ~/.config/nvim
else
    echo "info: updating LazyVim..."
    pushd ~/.config/nvim || exit
    git pull
    popd || exit
fi
echo "info: adding our lua scripts..."
rsync -av lua/ ~/.config/nvim/lua/
