# https://github.com/catppuccin/alacritty?tab=readme-ov-file
# import = ["~/.config/alacritty/catppuccin-mocha.toml"]
# import = ["~/.config/alacritty/rooprob-catppuccin-macchiato.toml"]
import = ["~/.config/alacritty/falcon.toml"]

[font]
size = 9

[font.normal]
family = "BlexMono Nerd Font Mono"

[window]
decorations = "none"

[window.padding]
x = 7
y = 0
