#!/bin/bash
# basic install script
# author: robf
#

things="alacritty bash fonts frame i3status keyboard llamafile lazyvim scripts second starship sway tmux"

log() {
    echo "$1"
}

run_setup() {
    log "🍺 $1"
    pushd "$1" || exit
    ./setup
    popd || exit
}

for thing in $things; do
    run_setup "$thing"
done
