#!/bin/bash
# vim: set ft=sh:

_create_dir() {
	echo "log: checking $1"
	[ ! -d "$1" ] && mkdir -p "$1"
}

# second brain
if [ ! -e "$HOME/.config/second/home" ]; then
	echo "error: you must configure ~/.config/second/home"
	exit 1
fi
source $HOME/.config/second/home

_create_dir "$SECOND_HOME"

# kindle-highlights
_create_dir "$KINDLE_HOME"

# website
_create_dir "$WEBSITE_HOME"
_create_dir "$BLOG_HOME"
