#!/bin/bash
# vim: set ft=sh:
#
# requires: ~/.config/second/home exports into shell, see ~/.zshrc

if [ -z "$SECOND_HOME" ]; then
	echo "❌SECOND_HOME not set!"
	exit 1
fi

_create_dir() {
	echo "🧠 installing $1"
	[ ! -d "$1" ] && mkdir -p "$1"
}

# second brain
_create_dir "$SECOND_HOME"

# kindle-highlights
_create_dir "$KINDLE_HOME"

# website
_create_dir "$WEBSITE_HOME"
_create_dir "$BLOG_HOME"
