#!/bin/bash

curl -LO -z nvim-linux64.tar.gz https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
sudo rm -fr /opt/nvim
sudo tar -C /opt -xzf nvim-linux64.tar.gz

if [ ! -d ~/.config/nvim ]; then
	git clone https://github.com/LazyVim/starter ~/.config/nvim
else
	pushd ~/.config/nvim || exit
	git pull
	popd || exit
fi

rsync -av init.lua ~/.config/nvim/
rsync -av --delete lua/ ~/.config/nvim/lua/
