#!/bin/bash
# set -x

OPTSTRING=":X"

NUKE_LAZYVIM=${NUKE_LAZYVIM:-}

while getopts ${OPTSTRING} opt; do
    case ${opt} in
    X)
        NUKE_LAZYVIM=1
        ;;
    esac
done

if [ ! -z "$NUKE_LAZYVIM" ]; then
    echo "info: nuking old config..."
    if [ -d "$HOME/.local/share/nvim" ]; then
        rm -fr "$HOME/.local/share/nvim"
    fi
    if [ -d "$HOME/.config/nvim" ]; then
        rm -fr "$HOME/.config/nvim"
    fi
fi

if [ ! -d ~/.config/nvim ]; then
    mkdir ~/.config/nvim
fi
echo "info: adding our lua scripts..."
rsync -av init.lua ~/.config/nvim/
rsync -av lua/ ~/.config/nvim/lua/
