#!/bin/bash

cp keyboard.default /etc/default/keyboard
dpkg-reconfigure keyboard-configuration
gsettings get org.gnome.desktop.input-sources xkb-options
gsettings set org.gnome.desktop.input-sources xkb-options "['ctrl:nocaps']"
