#!/bin/bash
# vim: set filetype=sh :
# author: robf
# description: generate blog script
# date: 2024-04-24

if [ -z "$BLOG_HOME" ]; then
	echo "error: you must configure ~/.config/second/home"
	exit 1
fi

# Check the value of the first parameter
case "$1" in
zet)
	# publish the zet

	;;
article)
	# publish articles

	;;

reset)
	pushd "$BLOG_HOME" || exit
	hugo new site "$BLOG_HOME"
	hugo server --disableFstRender
	;;

publish) ;;

*)
	# Print an error message if the parameter was not "zet" or "article"
	echo "usage: blog zet|article|publish"
	;;
esac
