#!/bin/bash
# vim: set filetype=sh :
# author: robf
# description: simple notes creating script
# date: 2024-04-08

TODAY=$(date -I)
DATETIME=$(date +'%Y-%m-%dT%H:%M:%S%Z')
HASH=$(date | sha256sum | cut -c 1-8 | tr -d '\n')

section="${SECTION:-zet}"
title="${TITLE:-$HASH}"

if [ -z "$SECOND_HOME" ]; then
    echo "error: you must configure ~/.config/second/home"
    exit 1
fi

SECTION_DIR=$SECOND_HOME/$section
[ ! -d "$SECTION_DIR" ] && mkdir -p "$SECTION_DIR"

filename=$SECTION_DIR/${title}.md
echo "[$title]($filename)"

INPUT=${@:-$(cat -)}

if [ ! -e "$filename" ]; then
    cat >"$filename" <<TEMPLATE
---
title: $title
author: $USER
section: $section
date: $TODAY
labels:

---
# $title

$INPUT

---

TEMPLATE
fi

GP=$(ps -o ppid= -p $PPID | xargs -n 1 ps -o ppid=,comm= -p)

# echo $GP

if ! echo "$GP" | grep nvim >/dev/null; then
    nvim "$filename"
fi
