#!/bin/bash

setting=$@

CPUFREQ=/sys/devices/system/cpu/cpu*/cpufreq/scaling_governor


if [ -z "$setting" ]; then
    # report
    sudo tlp-stat -s
    sudo tlp-stat -b
    sudo tlp-stat -p

	cat $CPUFREQ
	sudo cat /sys/kernel/debug/pmc_core/package_cstate_show

elif [ "$setting" = "powersave" ];then
    sudo tlp bat
    echo $setting | sudo tee -a  $CPUFREQ

    echo 1 | sudo tee -a /sys/devices/system/cpu/intel_pstate/no_turbo
    echo 5 | sudo tee -a /sys/devices/system/cpu/intel_pstate/min_perf_pct
    echo 33 | sudo tee -a /sys/devices/system/cpu/intel_pstate/max_perf_pct

elif [ "$setting" = "performance" ];then
    sudo tlp start
    echo $setting | sudo tee -a  $CPUFREQ

    echo 0 | sudo tee -a /sys/devices/system/cpu/intel_pstate/no_turbo
    echo 5 | sudo tee -a /sys/devices/system/cpu/intel_pstate/min_perf_pct
    echo 100 | sudo tee -a /sys/devices/system/cpu/intel_pstate/max_perf_pct
fi



