#!/bin/bash
set -euo pipefail

mkdir -p "$HOME/.config/tmux/plugins"

[ -d "$HOME/.config/tmux/plugins/tpm" ] || git clone https://github.com/tmux-plugins/tpm "$HOME/.config/tmux/plugins/tpm"
pushd "$HOME/.config/tmux/plugins/tpm" >/dev/null || exit
git pull --ff-only
popd >/dev/null || exit

cp tmux.conf "$HOME/.config/tmux/tmux.conf"
rsync -a plugins/falcon-tmux "$HOME/.config/tmux/plugins"

if command -v tmux >/dev/null 2>&1; then
    tmux source-file "$HOME/.config/tmux/tmux.conf" || true
fi

echo "in tmux Ctr-b + I to install plugins"
