#!/bin/bash

[ -d ~/.config/tmux ] || mkdir ~/.config/tmux
[ -d ~/.config/tmux/plugins ] || mkdir ~/.config/tmux/plugins

[ -d ~/.config/tmux/plugins/tpm ] || git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm
pushd ~/.config/tmux/plugins/tpm
git pull
popd
cp tmux.conf ~/.config/tmux/tmux.conf

tmux source-file ~/.config/tmux/tmux.conf || true

